# Generated by Django 5.1.6 on 2025-03-13 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_comment_user_item_user_alter_item_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='found_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='item',
            name='contact_email',
        ),
    ]
