# Generated by Django 5.1.6 on 2025-03-14 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_rename_found_date_item_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], default='lost', max_length=10),
        ),
    ]
